ofek/bit

bit/network/fees.py
bit/wallet.py
docs/source/guide/fees.rst
docs/source/guide/transactions.rst

21.co has rebraded to earn.com. This converts all 21.co URLs to
earn.com.
Prior to this commit, if requesting say over Tor bit would try to
parse json on the 4XX reply returned by earn.com's CloudFlare
service. Now, we raise an exception on such status codes and
proceed to use the fee constant.

21.co -> earn.com, don't parse fee json on non 2XX status

---

bit/network/services.py

smartbit's API actually takes direct JSON, not the typical POST
format. Thus, smartbit was never used for broadcasts.
Also reorders API usage consistently to Bitpay first, Smartbit
second, and Blockchain last. Blockchain is notoriously
unreliable. I have seen it go down many times and be several
hours behind in others.
Today while testing, repeatedly it returned a 200 for pushtx and
yet the transaction was not pushed to the network. I pushed it
with smartbit and could even then find it on Blockchain, itself.
Sending a 200 for a transaction that was not pushed is completely
unacceptable from a programatic usage standpoint as no other
APIs will be used in turn. Hopefully, this reordering should
help minimize any Blockchain "oddities" as it will be the last
API in line.

broadcast_tx: Fix smartbit pushtx usage, also reorder services

---

bit/format.py
tests/samples.py
tests/test_format.py
tests/test_wallet.py

We don't yet support pay2sh. Until #12 is ready, we should throw
exceptions if given an address in an unexpected format.

Closes #23 - Raise exception when using pay2sh addresses

---

.gitignore
bit/network/fees.py
bit/transaction.py
tests/test_transaction.py

Before this commit there was an issue where combine=False send()'s
would calculate the fee with all unspents. Now it will recalculate
the fee as it goes along adding unspents to use the minimum number
of unspents and the smallest fee.
Note that is this is very unoptimized and some unspents add more
fees than they are worth.
Adds one test case that was not broken before this point and another
for validating that additional, unnecessary unspents do not raise
the fee.
Also introduce logging, add warnings if the fee API cannot be reached
and the default or cached is used.
The warnings will only be seen in some cases depending on the logging
level set, but are always caught with failing test cases and can
further aid in debugging.

Fixes #30: Calculate fee with only used unspents, warn about default fee

---

bit/utils.py

Due to some discrepance between forks I found this little bug in the merge commit. When parsing a partially-signed multisig transaction it can otherwise not extract the signatures from the scriptSig correctly.
At some point the code within the function get_signature_from_script probably has to be refactored.

Small fix for parsing partially-signed script from transaction

---

bit/wallet.py

Queries the NetworkAPI only for (compressed) keys that have a segwit address. Prior it would query the API with the segwit address `None`.

Fixes query of NetworkAPI for segwit address

---

bit/constants.py
tests/test_transaction.py

Ever since Bitcoin Core 0.11.x the OP_RETURN function allows 80 bytes of data to be written to a transaction.
https://bitcoin.org/en/developer-guide#term-null-data

Change MESSAGE_LIMIT to 80

---

bit/network/services.py
tests/network/test_services.py

**What is this?**
This PR adds two new calls onto `NetworkAPI`: `get_transaction_by_id` and `get_transaction_by_id_testnet`. Both calls return a `TxObj`. Each api service has been extended to take advantage of their "raw tx" api calls. In addition, new tests have been written for each service as well as for `NetworkAPI` itself.
**Why?**
I'm already using this lib to access the blockchain, but I needed a way to grab individual transactions directly by their `txid`. This lib had everything I already needed to contact multiple apis, so rather than reinvent the wheel, I've extended this library to include the functionality I was missing.
**Why should this be merged?**
The added functions fit well with the rest of the library thematically. In addition, `get_transactions` only returns the …

Add `get_transaction_by_id` calls

---

bit/constants.py
bit/exceptions.py
bit/network/rates.py
bit/network/services.py
docs/source/guide/network.rst
docs/source/guide/remotenode.rst
docs/source/index.rst
setup.py
tests/network/test_services.py
tox.ini

This PR adds a method allowing the `NetworkAPI` to connect to a remote Bitcoin node instead of relying on web APIs. It is marked as a work-in-progress to allow testing, code improvements and test cases to be added. 
It has been implemented in a way to minimize changes to the codebase and to not break already existing tests. Any suggestions however on how to better connect the new class `bit.network.services.RPCHost` with the `NetworkAPI` is welcome! Right now inside `NetworkAPI` it simply overrides its web-API values using the `RPCHost` instead.
This implementation also allows to connect to two different Bitcoin nodes: one for mainnet and one for testnet; and keeps them separate.
```python
import bit
from bit.network import NetworkAPI
NetworkAPI.connect_to_node(user='user', …
```

[WIP] Adds support for `NetworkAPI` to use a remote Bitcoin node

---

bit/transaction.py
bit/wallet.py

This PR adds a new parameter `is_raw` onto the method `send` and all calling methods
When you send a message in a transaction, `send` converts the message text into hexadecimal. If you have a message that is already hexadecimal, then it gets unnecessarily converted causing the message to double in length.
Being able to pass a message in as hexadecimal reduces overhead and requires less effort on both sides.

Add support for passing raw hexadecimal messages to `send`

---

bit/transaction.py
bit/wallet.py
tests/test_transaction.py

**Unexpected behavior can occur when calling `create_transaction` with `combine=False` and `absolute_fees=True`.**
The method `select_coins` tries to find a perfect match for the transaction amount in the [first step](https://github.com/ofek/bit/blob/master/bit/transaction.py#L300). Here it passes the fee to `branch_and_bound` without further checks. However, `branch_and_bound` tries to calculate a `target_to_match` based on the passed fee implicitly assuming the unit is sats/byte. This yields to wrong target calculations and can accidentally match a much larger input. 
If this false match occurs, bad things happen after returning from `branch_and_bound` in [line 305](https://github.com/ofek/bit/blob/master/bit/transaction.py#L305), where `remaining` is set to zero. 
This has the result …

Critical Bug: branch_and_bound is incompatible with absolute fees

---

docs/source/dev/api.rst
docs/source/guide/network.rst

This just fixes a few typos in the documentation that I found.
BTW @ofek I am not sure if there is some issue with the credentials used to auto-generate the Github Pages (https://travis-ci.org/github/ofek/bit/jobs/706876817#L668)?

fix small documentation typos

---

bit/network/services.py

New formula takes into account that response['utxo'][0]['block_id'] will be set to -1 if the transaction is pending and the block height if mined.
Fixes #119

Fix Unspent.confirmations from Blockchair API

---

bit/network/meta.py
bit/transaction.py
bit/wallet.py
docs/source/guide/transactions.rst
tests/network/test_meta.py
tests/test_transaction.py

This PR combines the two RBF implementation ideas (#122 and #123) and adds two tests to verify this new code.
Key changes of this PR:
* key.send(), key.create_transaction() and Key.prepare_transaction() now have a new optional boolean argument `replace_by_fee` which defaults to `False`.
* Unspent class has extra attribute `sequence` which defaults to constants.SEQUENCE (as in #123) and as a new opt_in_for_RBF() method.
* sanitize_tx_data() receives the new `replace_by_fee` argument and calls unspent.opt_in_for_RBF() if set to true.
* create_new_transaction() reads unspent.sequence and passes it into the inputs.
* the added tests are based in a mined RBF transaction that has two segwit inputs which is tested against the generated raw transactions (without the witnesses).
I ran all tests …

Add tests and support for replace-by-fee (BIP 125).

---

bit/network/services.py

#120 only fixed BlockchairAPI.get_unspent(), this also fixes for testnet as mentioned in #127
BlockstreamAPI seems to set confirmations to 0 when the transaction has just been mined. When block_height == tx["status"] ["block_height"], there is one confirmation, not zero.
Closes #127

Fix confirmations from BlockchairAPI.get_unspent_testnet() and BlockstreamAPI

---

bit/network/services.py

I haven't used bit for almost a month, but today I ran some code that uses bit. I noticed that the number of confirmations on my utxos was -1 like reported in issues #127 and #137. When I started digging into the cause of the problem, I found a much bigger problem: bitcoreAPI is returning non-existent UTXOs. This issue probably arises when using RBF transactions and doing fee bumping. Therefore it went undetected for such a long time. Check for yourselves:
`> https://api.bitcore.io/api/BTC/mainnet/address/32KiQZVWb4oSC1Urfa7CNr1kzVjMbPg4Yu/?unspent=true&limit=100`
```json
[
{"_id":"5f6a0d41c1032d4686c88b7f","chain":"BTC","network":"mainnet","coinbase":false,"mintIndex":1,"spentTxid":"","mintTxid":"6b5b2d0325b3e39a02ab5dbd26fbe5ab7796aa867f0804057d94bc8c786107d6","mintHeight":649506,"spentH …
```

URGENT: Downgrade BitCoreAPI

---

docs/source/guide/keys.rst

Some data attributes are incorrectly marked as methods in the Sphinx documentation.

Correct Documentation

---

bit/network/fees.py

This pull request changes the fee provider from bitcoinfees.earn.com to mempool.space and fixes [#152](https://github.com/ofek/bit/issues/152).
The current fee provider (bitcoinfees.earn.com) is often suggesting network fees that are an order of magnitude greater than providers such as Blockchair, Blockstream, Mempool.space, as well as Bitcoin Core. This is unnecessarily wasteful, and even the "slow" network fee is high enough to be a next-block confirmation fee, usually actually two or three times *more* than the prevailing next-block fee.
I selected Mempool.space because of its seemingly unlimited API limit. At least, I didn't run into its API limit during testing.

Change fee provider

---

bit/wallet.py

Your fees calculator uses https://mempool.space/api/v1/fees/recommended instead of https://bitcoinfees.earn.com so I thought to update this on param description

update fee param docstring with correct url

---

bit/wallet.py
docs/source/guide/fees.rst
docs/source/guide/transactions.rst

After the PR (https://github.com/ofek/bit/pull/155), the comments and docs are not updated with mempool.space from bitcoinfees.earn.com.
With this PR, it's changed to the updated url.
POV: It helps the doc readers.

Update Docs and comments
